version: '3.8'

services:
  backend:
    container_name: backend
    build: .
    working_dir: /usr/src/app
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm start"
