version: '3.8'

services:
  backend:
    container_name: backend
    image: node:20
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    command: >
      sh -c "npm install && npm run build && npm start"
 
