name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: isleofsky76/englishwitheasyword-backend
          stage: main
          yaml: |
            name: englishwitheasyword-backend
            app: node@20
            options:
              env:
                - name: NODE_ENV
                  value: production
                - name: OPENAI_API_KEY
                  secret: OPENAI_API_KEY
                - name: ADMIN_PASSWORD
                  secret: ADMIN_PASSWORD
                - name: MONGO_URI
                  secret: MONGO_URI
              ports: 3000
              start: node index.js
              install: npm ci --production
              healthz: /healthz
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
