name: Deploy to Cloudtype

on:
  push:
    branches:
      - main  # 배포를 트리거할 브랜치 이름

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # actions/checkout 최신 버전 사용

    - name: Set up Node.js 20
      uses: actions/setup-node@v3  # actions/setup-node 최신 버전 사용
      with:
        node-version: '20'

    - name: Deploy to Cloudtype
      env:
        CLOUDTYPE_API_KEY: ${{ secrets.CLOUDTYPE_API_KEY }}
        MONGO_URI: ${{ secrets.MONGO_URI }}
        ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
      run: |
        curl -X POST "https://api.cloudtype.io/deploy" \
        -H "Authorization: Bearer $CLOUDTYPE_API_KEY" \
        -H "Content-Type: application/json" \
        -d '{
              "repository": "https://github.com/isleofsky76/englishwitheasyword_backend.git",
              "branch": "main",
              "commands": [
                "cd backend",
                "docker-compose down",
                "docker-compose up -d"
              ],
              "environment": {
                "MONGO_URI": "$MONGO_URI",
                "ADMIN_PASSWORD": "$ADMIN_PASSWORD"
              }
            }'
