name: Deploy to Cloudtype

on:
  push:
    branches:
      - main  # 배포를 트리거할 브랜치 이름

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Cloudtype
      env:
        CLOUDTYPE_API_KEY: ${{ secrets.CLOUDTYPE_API_KEY }}
      run: |
        curl -X POST "https://api.cloudtype.io/deploy" \
        -H "Authorization: Bearer $CLOUDTYPE_API_KEY" \
        -H "Content-Type: application/json" \
        -d '{
              "repository": "https://github.com/your_username/your_repo.git",
              "branch": "main",
              "commands": [
                "cd backend",
                "docker-compose down",
                "docker-compose up -d"
              ]
            }'
